# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Laputa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Laputa
  pod 'SwiftSH'

  target 'LaputaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LaputaUITests' do
    # Pods for testing
  end

end
